### ISSUE TITLE
Implementar la librería faker.js

### ISSUE THREAD

**Issue by juan-volpe** [upex-galaxy/upex-cypress-spacebeyond#17]
Hola buenas tardes, se podría impletamentar la librería faker.js para utilizar names random, entre otras cosas.

Dejo la documentación correspondiente:
https://fakerjs.dev/
https://www.npmjs.com/package/@faker-js/faker
https://github.com/faker-js/faker

Saludos
Juan

**Comment by saiotest** [comment]
Listo ✅ Agregada a todas las Ramas!
